image: golang:1.18

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: $POSTGRES_DB
  POSTGRES_USER: $POSTGRES_USER
  POSTGRES_PASSWORD: $POSTGRES_PASSWORD
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - env
  - test
  - build

dependencies:
  stage: env
  script:
    - echo $DATABASE_USER
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.1
    - mkdir ./bin | curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-arm64.tar.gz | tar xvz -C ./bin
    - make deps
    - make build_focus
  artifacts:
    paths:
    - ./bin/migrate
    - ./bin/focus

migrations:
  stage: env
  needs: ['dependencies']
  dependencies:
    - dependencies
  script:
    - ./bin/focus migrate

unit_tests:
  stage: test
  needs: ['migrations']
  dependencies: 
    - migrations

  script:
    - make test

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make build