image: golang:1.18

stages:
  - test
  - build

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.1
  - make deps

unit_tests:
  stage: test
  script:
    - make test

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make build