image: golang:1.18

stages:
  - env
  - test
  - build

services:
  - postgres:latest

variables:
  ENV: test
  POSTGRES_DB: 'test'
  POSTGRES_USER: 'postgres'
  POSTGRES_PASSWORD: 'postgres'

dependencies:
  stage: env
  script:
    - echo $DATABASE_USER
    - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.46.1
    - mkdir ./bin | curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-arm64.tar.gz | tar xvz -C ./bin
    - make deps
    - make build_focus
  artifacts:
    paths:
    - ./bin/migrate
    - ./bin/focus

migrations:
  stage: env
  needs: ['dependencies']

  variables:
    DATABASE_NAME: $POSTGRES_DB
    DATABASE_USER: $POSTGRES_USER
    DATABASE_PASSWORD: $POSTGRES_PASSWORD
    DATABASE_HOST: postgres

  script:
    - ./bin/focus migrate

unit_tests:
  stage: test
  needs: ['migrations']

  script:
    - make test

lint_code:
  stage: test
  script:
    - make lint

build:
  stage: build
  script:
    - make build