name = "test"
debug = false

[database]
dsn="postgres://postgres:postgres@localhost:5432/program_dev?sslmode=disable"
user = "postgres"
password = "postgres"
Host = "localhost"
port = 5432
name = "program_dev"